/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp.form;

import java.awt.CardLayout;
import java.awt.KeyboardFocusManager;
import java.awt.Rectangle;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JViewport;
import sp.util.CardLayoutController;
import sp.util.FormControl;

/**
 *
 * @author Thosan Girisona S
 */
public class FixedQuest extends javax.swing.JPanel {

    /**
     * Creates new form TesQuest
     */

    public FixedQuest() {
        initComponents();
    }

    public Hal1 getHal12() {
        return hal12;
    }

    public void setHal12(Hal1 hal12) {
        this.hal12 = hal12;
    }

    public Hal2 getHal21() {
        return hal21;
    }

    public void setHal21(Hal2 hal21) {
        this.hal21 = hal21;
    }

    public Hal3 getHal31() {
        return hal31;
    }

    public void setHal31(Hal3 hal31) {
        this.hal31 = hal31;
    }

    public Hal4 getHal41() {
        return hal41;
    }

    public void setHal41(Hal4 hal41) {
        this.hal41 = hal41;
    }

    public Hal5 getHal51() {
        return hal51;
    }

    public void setHal51(Hal5 hal51) {
        this.hal51 = hal51;
    }

    public Hal6 getHal61() {
        return hal61;
    }

    public void setHal61(Hal6 hal61) {
        this.hal61 = hal61;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        hal12 = new sp.form.Hal1();
        jScrollPane6 = new javax.swing.JScrollPane();
        hal21 = new sp.form.Hal2();
        jScrollPane10 = new javax.swing.JScrollPane();
        hal31 = new sp.form.Hal3();
        jScrollPane8 = new javax.swing.JScrollPane();
        hal41 = new sp.form.Hal4();
        jScrollPane9 = new javax.swing.JScrollPane();
        hal51 = new sp.form.Hal5();
        jScrollPane11 = new javax.swing.JScrollPane();
        hal61 = new sp.form.Hal6();

        setLayout(new java.awt.CardLayout());

        jScrollPane3.setViewportView(hal12);

        add(jScrollPane3, "hal1");

        jScrollPane6.setViewportView(hal21);

        add(jScrollPane6, "hal2");

        jScrollPane10.setViewportView(hal31);

        add(jScrollPane10, "hal3");

        jScrollPane8.setViewportView(hal41);

        add(jScrollPane8, "hal4");

        jScrollPane9.setViewportView(hal51);

        add(jScrollPane9, "hal5");

        jScrollPane11.setViewportView(hal61);

        add(jScrollPane11, "hal6");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sp.form.Hal1 hal12;
    private sp.form.Hal2 hal21;
    private sp.form.Hal3 hal31;
    private sp.form.Hal4 hal41;
    private sp.form.Hal5 hal51;
    private sp.form.Hal6 hal61;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables

}
