/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp.form;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.Rectangle;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import sp.component.TextField;
import sp.controller.SaveController;
import sp.controller.UpdateController21;
import sp.controller.UpdatingController;
import sp.model.B1;
import sp.model.B2;
import sp.model.B3;
import sp.model.B4;
import sp.util.CardLayoutController;
import sp.util.CheckConnection;
import sp.util.ErrorControl;
import sp.util.FormControl;
import sp.util.LogMessage;
import sp.util.UserControl;

/**
 *
 * @author Thosan Girisona S
 */
public class YPane extends javax.swing.JPanel {

    /**
     * Creates new form TesQuest
     */
    UpdateController21 con;
    CardLayoutController clc;
    ArrayList limitSection = new ArrayList();
    int endPos = 0;
    B1 b1;
    B2 b2;
    B3 b3;
    B4 b4;
    SaveController ac;
    FixedQuest fq;

    public YPane() {
        initComponents();
        registerCard();
        setScrollListener(fixedQuest1);
        newDoc();
        newDoc1();
        initListener();
    }

    public JTextArea getLogText() {
        return logText;
    }

    public void addLogText(String log) {
        this.logText.append(log);
    }

    public FixedQuest getFq() {
        return fq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        nimField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        fixedQuest1 = new sp.form.FixedQuest();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tablePane1 = new sp.form.TablePane();
        welcomeLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TesQuest");

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(">>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nimField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(nimField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        logText.setColumns(20);
        logText.setRows(5);
        jScrollPane2.setViewportView(logText);

        jScrollPane1.setViewportView(fixedQuest1);

        jLabel2.setText("Log Text:");

        jButton1.setText("Save NIM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Ganti NIM");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        welcomeLbl.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        welcomeLbl.setText("Don't Forget to Login");

        sp.model.TableErrorModel model = new sp.model.TableErrorModel();
        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel4.setText("Tabel Error");

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel5.setText("Updating table");

        jButton7.setText("Update..!!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addComponent(jLabel4)
                    .addComponent(tablePane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jButton6))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(tablePane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    public FixedQuest getFixedQuest1() {
        return fixedQuest1;
    }

    public void setFixedQuest1(FixedQuest fixedQuest1) {
        this.fixedQuest1 = fixedQuest1;
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        getClc().next();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getClc().previous();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nim = nimField.getText();
        UserControl.setNim(nim);
        nimField.setBackground(Color.GRAY);
        nimField.setEditable(false);
        CheckConnection.createConnection();
        welcomeLbl.setText("Connected");
        LogMessage.clearLog();
        try {
            LogMessage.write("Login");
        } catch (IOException ex) {
            Logger.getLogger(YPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        nimField.setBackground(null);
        nimField.setEditable(true);
        CheckConnection.closeConnection();
        try {
            LogMessage.write("Logout\n-----------------------------------------------------------------");
        } catch (IOException ex) {
            Logger.getLogger(YPane.class.getName()).log(Level.SEVERE, null, ex);
        }
        UserControl.logOut();
        welcomeLbl.setText("Don't Forget to Login");
        tablePane1.clearTable();
        tablePane1.getLoad().setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        int hal = (int) jTable1.getModel().getValueAt(baris, 2);
//        TextField tf = (TextField) jTable1.getModel().getValueAt(baris, 0);
        switch (hal) {
            case 1:
                FormControl.getController().show("hal1");
                break;
            case 2:
                FormControl.getController().show("hal2");
                break;
            case 3:
                FormControl.getController().show("hal3");
                break;
            case 4:
                FormControl.getController().show("hal4");
                break;
            case 5:
                FormControl.getController().show("hal5");
                break;
            case 6:
                FormControl.getController().show("hal6");
                break;
            default:
                FormControl.getController().show("hal1");
                break;
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private sp.form.FixedQuest fixedQuest1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea logText;
    private javax.swing.JTextField nimField;
    private javax.swing.JButton saveBtn;
    private sp.form.TablePane tablePane1;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables

    private void registerCard() {
        clc = getClc();
        clc.setCardLayout((CardLayout) fixedQuest1.getLayout());
        clc.setParentCard(fixedQuest1);

        FormControl.init(fixedQuest1, clc);
        endPos += fixedQuest1.getHal12().getMaxPertanyaan() - 1;
        limitSection.add(0, endPos);
        endPos += fixedQuest1.getHal21().getMaxPertanyaan();
        limitSection.add(1, endPos);
        endPos += fixedQuest1.getHal31().getMaxPertanyaan();
        limitSection.add(2, endPos);
        endPos += fixedQuest1.getHal41().getMaxPertanyaan();
        limitSection.add(3, endPos);
        endPos += fixedQuest1.getHal51().getMaxPertanyaan();
        limitSection.add(4, endPos);
        endPos += fixedQuest1.getHal61().getMaxPertanyaan();
        limitSection.add(5, endPos);
        FormControl.setLimitSection(limitSection);
    }

    public CardLayoutController getClc() {
        if (clc == null) {
            return new CardLayoutController();
        } else {
            return clc;
        }
    }

    public void setClc(CardLayoutController clc) {
        this.clc = clc;
    }

    private void clearForm() {
        getClc().first();
        FormControl.clearAll();
    }

    private void setScrollListener(JPanel aThis) {
        KeyboardFocusManager.getCurrentKeyboardFocusManager().
                addPropertyChangeListener("focusOwner", new PropertyChangeListener() {

                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {

                        if (!(evt.getNewValue() instanceof JComponent)) {
                            return;
                        }

                        JViewport viewport = (JViewport) aThis.getParent();
                        JComponent focused = (JComponent) evt.getNewValue();
                        if (aThis.isAncestorOf(focused)) {
                            Rectangle rect = focused.getBounds();
                            Rectangle r2 = viewport.getVisibleRect();
                            //System.out.println(aThis);
                            aThis.scrollRectToVisible(new Rectangle(rect.x, rect.y - 200, (int) r2.getWidth(), (int) r2.getHeight()));
                        }
                    }
                });
    }

    private void newDoc() {
        fq = getFixedQuest1();
        b1 = new B1();
        b2 = new B2();
        b3 = new B3();
        b4 = new B4();
        ac = new SaveController(b1, b2, b3, b4,
                fq.getHal12(),
                fq.getHal21(),
                fq.getHal31(),
                fq.getHal41(),
                fq.getHal51(),
                fq.getHal61(),
                this, jTable1);
        saveBtn.addActionListener(ac);
    }

    private void initListener() {
        con = new UpdateController21(this);
        tablePane1.getLoad().addActionListener(con);
        tablePane1.getRefresh().addActionListener(con);
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public TablePane getTablePane1() {
        return tablePane1;
    }

    private void newDoc1() {
        fq = getFixedQuest1();
        b1 = new B1();
        b2 = new B2();
        b3 = new B3();
        b4 = new B4();
        UpdatingController uc;
        uc = new UpdatingController(b1, b2, b3, b4,
                fq.getHal12(),
                fq.getHal21(),
                fq.getHal31(),
                fq.getHal41(),
                fq.getHal51(),
                fq.getHal61(),
                this, jTable1);
        jButton7.addActionListener(uc);
    }
}
