/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp.form;

import java.util.ArrayList;
import javax.swing.JLayeredPane;
import sp.component.TextField;
import sp.util.FormControl;

/**
 *
 * @author Rohma Hidayati [12.7363]
 */
public class Hal2Listing extends javax.swing.JPanel {

    /**
     * Creates new form Hal2Listing
     */
    private ArrayList<TextField> listTextFieldHal2Listing = new ArrayList<TextField>();
    protected static int startPos = Hal1Listing.maxPos;
    protected static int maxPos;

    public Hal2Listing() {
        initComponents();
        addListTextfield();
        setListTextFieldHal2Listing(FormControl.setFixedPos(startPos, getListTextField()));
    }

    public int getMaxPertanyaan() {
        return maxPos;
    }

    public ArrayList<TextField> getListTextField() {
        return listTextFieldHal2Listing;
    }

    //    public void setFieldHal1(B2Listing b) {
//        b4r1.setText(b.getB4r1());
//        b4r2s1.setText(b.getB4r2s1());
//        b4r2s2.setText(b.getB4r2s2());
//        b4r2s3.setText(b.getB4r2s3());
//        b4r3.setText(b.getB4r3());
//        b4r4.setText(b.getB4r4());
//        b4r5.setText(b.getB4r5());
//        b4r6.setText(b.getB4r6());
//    }
    private void addListTextfield() {
        getListTextField().add(0, b4r2s1);
        getListTextField().add(1, b4r2s2);
        getListTextField().add(2, b4r2s3);
        getListTextField().add(3, b4r3);
        getListTextField().add(4, b4r4);
        getListTextField().add(5, b4r5);
        getListTextField().add(6, b4r6);
        maxPos = getListTextField().size();
    }

    public ArrayList<TextField> getListTextFieldHal2Listing() {
        return listTextFieldHal2Listing;
    }

    public void setListTextFieldHal2Listing(ArrayList<TextField> listTextFieldHal2Listing) {
        this.listTextFieldHal2Listing = listTextFieldHal2Listing;
    }

    public static int getStartPos() {
        return startPos;
    }

    public static void setStartPos(int startPos) {
        Hal2Listing.startPos = startPos;
    }

    public static int getMaxPos() {
        return maxPos;
    }

    public static void setMaxPos(int maxPos) {
        Hal2Listing.maxPos = maxPos;
    }

    public TextField getB4r2s1() {
        return b4r2s1;
    }

    public void setB4r2s1(TextField b4r2s1) {
        this.b4r2s1 = b4r2s1;
    }

    public TextField getB4r2s2() {
        return b4r2s2;
    }

    public void setB4r2s2(TextField b4r2s2) {
        this.b4r2s2 = b4r2s2;
    }

    public TextField getB4r2s3() {
        return b4r2s3;
    }

    public void setB4r2s3(TextField b4r2s3) {
        this.b4r2s3 = b4r2s3;
    }

    public TextField getB4r3() {
        return b4r3;
    }

    public void setB4r3(TextField b4r3) {
        this.b4r3 = b4r3;
    }

    public TextField getB4r4() {
        return b4r4;
    }

    public void setB4r4(TextField b4r4) {
        this.b4r4 = b4r4;
    }

    public TextField getB4r5() {
        return b4r5;
    }

    public void setB4r5(TextField b4r5) {
        this.b4r5 = b4r5;
    }

    public TextField getB4r6() {
        return b4r6;
    }

    public void setB4r6(TextField b4r6) {
        this.b4r6 = b4r6;
    }

    public sp.imageClass.Hal2Listing getHal2Listing1() {
        return hal2Listing1;
    }

    public void setHal2Listing1(sp.imageClass.Hal2Listing hal2Listing1) {
        this.hal2Listing1 = hal2Listing1;
    }

    public JLayeredPane getjLayeredPane1() {
        return jLayeredPane1;
    }

    public void setjLayeredPane1(JLayeredPane jLayeredPane1) {
        this.jLayeredPane1 = jLayeredPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hal2Listing1 = new sp.imageClass.Hal2Listing();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        b4r2s1 = new sp.component.TextField();
        b4r2s2 = new sp.component.TextField();
        b4r2s3 = new sp.component.TextField();
        b4r3 = new sp.component.TextField();
        b4r4 = new sp.component.TextField();
        b4r5 = new sp.component.TextField();
        b4r6 = new sp.component.TextField();

        setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b4r2s1.setAngka(true);
        b4r2s1.setMaxDigit(999);
        b4r2s1.setMinDigit(1);
        b4r2s1.setRequired(true);
        jLayeredPane1.add(b4r2s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 40, 30));

        b4r2s2.setAngka(true);
        b4r2s2.setMaxDigit(999);
        b4r2s2.setMinDigit(1);
        b4r2s2.setRequired(true);
        jLayeredPane1.add(b4r2s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 40, 30));

        b4r2s3.setAngka(true);
        b4r2s3.setMaxDigit(999);
        b4r2s3.setMinDigit(1);
        b4r2s3.setRequired(true);
        jLayeredPane1.add(b4r2s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 30));

        b4r3.setHuruf(true);
        b4r3.setLength(100);
        b4r3.setRequired(true);
        jLayeredPane1.add(b4r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, 30));

        b4r4.setHuruf(true);
        b4r4.setLength(5);
        b4r4.setRequired(true);
        jLayeredPane1.add(b4r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 80, 30));

        b4r5.setAngka(true);
        b4r5.setKhusus(true);
        b4r5.setKhususType('2');
        b4r5.setMaxDigit(64);
        b4r5.setMinDigit(15);
        b4r5.setRequired(true);
        jLayeredPane1.add(b4r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 40, 30));

        b4r6.setAngka(true);
        b4r6.setHuruf(true);
        b4r6.setLength(200);
        b4r6.setRequired(true);
        jLayeredPane1.add(b4r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 290, 30));

        javax.swing.GroupLayout hal2Listing1Layout = new javax.swing.GroupLayout(hal2Listing1);
        hal2Listing1.setLayout(hal2Listing1Layout);
        hal2Listing1Layout.setHorizontalGroup(
            hal2Listing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        hal2Listing1Layout.setVerticalGroup(
            hal2Listing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        add(hal2Listing1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sp.component.TextField b4r2s1;
    private sp.component.TextField b4r2s2;
    private sp.component.TextField b4r2s3;
    private sp.component.TextField b4r3;
    private sp.component.TextField b4r4;
    private sp.component.TextField b4r5;
    private sp.component.TextField b4r6;
    private sp.imageClass.Hal2Listing hal2Listing1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
