/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp.panelcomponent;

/**
 *
 * @author HP
 */
public class NavbarButton extends javax.swing.JPanel {

    /**
     * Creates new form NavbarButton
     */
    public NavbarButton() {
        initComponents();
        this.setOpaque(false);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutbutton1 = new sp.componentButton.Aboutbutton();
        homebutton1 = new sp.componentButton.Homebutton();
        listingbutton1 = new sp.componentButton.Listingbutton();
        logoutbutton1 = new sp.componentButton.Logoutbutton();
        questionnairebutton1 = new sp.componentButton.Questionnairebutton();

        aboutbutton1.setText("");
        aboutbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutbutton1MousePressed(evt);
            }
        });

        homebutton1.setText("");
        homebutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebutton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homebutton1MousePressed(evt);
            }
        });
        homebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutton1ActionPerformed(evt);
            }
        });

        listingbutton1.setText("");
        listingbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listingbutton1MousePressed(evt);
            }
        });

        logoutbutton1.setText("");
        logoutbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutbutton1MousePressed(evt);
            }
        });

        questionnairebutton1.setText("");
        questionnairebutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                questionnairebutton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionnairebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboutbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(listingbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(homebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listingbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionnairebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homebutton1ActionPerformed

    private void homebutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebutton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homebutton1MouseClicked

    private void aboutbutton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutbutton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutbutton1MousePressed

    private void homebutton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebutton1MousePressed
        getListingbutton1().resetButton();
        getAboutbutton1().resetButton();
        getLogoutbutton1().resetButton();
        getQuestionnairebutton1().resetButton();
    }//GEN-LAST:event_homebutton1MousePressed

    private void listingbutton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listingbutton1MousePressed
        getHomebutton1().resetButton();
        getAboutbutton1().resetButton();
        getLogoutbutton1().resetButton();
        getQuestionnairebutton1().resetButton();
    }//GEN-LAST:event_listingbutton1MousePressed

    private void logoutbutton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbutton1MousePressed
        getListingbutton1().resetButton();
        getAboutbutton1().resetButton();
        getHomebutton1().resetButton();
        getQuestionnairebutton1().resetButton();
    }//GEN-LAST:event_logoutbutton1MousePressed

    private void questionnairebutton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_questionnairebutton1MousePressed
        getListingbutton1().resetButton();
        getAboutbutton1().resetButton();
        getLogoutbutton1().resetButton();
        getHomebutton1().resetButton();
    }//GEN-LAST:event_questionnairebutton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sp.componentButton.Aboutbutton aboutbutton1;
    private sp.componentButton.Homebutton homebutton1;
    private sp.componentButton.Listingbutton listingbutton1;
    private sp.componentButton.Logoutbutton logoutbutton1;
    private sp.componentButton.Questionnairebutton questionnairebutton1;
    // End of variables declaration//GEN-END:variables
 public sp.componentButton.Aboutbutton getAboutbutton1() {
        return aboutbutton1;
    }

    /**
     * @return the homebutton1
     */
    public sp.componentButton.Homebutton getHomebutton1() {
        return homebutton1;
    }

    /**
     * @return the listingbutton1
     */
    public sp.componentButton.Listingbutton getListingbutton1() {
        return listingbutton1;
    }

    /**
     * @return the logoutbutton1
     */
    public sp.componentButton.Logoutbutton getLogoutbutton1() {
        return logoutbutton1;
    }

    /**
     * @return the questionnairebutton1
     */
    public sp.componentButton.Questionnairebutton getQuestionnairebutton1() {
        return questionnairebutton1;
    }
}
