/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp.view;

import javax.swing.JLabel;
import sp.controller.LandingMenuControllerTest;

/**
 *
 * @author Tiara Ratna Dewi [12.7403]
 */
public class Panel extends javax.swing.JPanel {

    private LandingMenuControllerTest controller;

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        navbarButton1.getHomebutton1().setActive(true);
        menuListing.getUpdatebutton1().setActive(false);
        controller = new LandingMenuControllerTest(getEntryListing(), getDataEntryQuest1(), getUpdateListing1(), updateQuest1, this, MainPanel, getMenuListing(), getMenuQuest(), landingButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new sp.background.Background();
        MainPanel = new javax.swing.JPanel();
        landingButton1 = new sp.panelcomponent.LandingButton();
        menuQuest = new sp.panelcomponent.Menu();
        EntryListing = new sp.panelcomponent.DataEntryListing();
        EntryQuest = new sp.panelcomponent.DataEntryQuest();
        updateListing1 = new sp.panelcomponent.UpdateListing();
        updateQuest1 = new sp.panelcomponent.UpdateQuest();
        menuListing = new sp.panelcomponent.Menu();
        navbarButton1 = new sp.panelcomponent.NavbarButton();
        closeminbutton1 = new sp.componentButton.Closeminbutton();
        minimizebutton1 = new sp.componentButton.Minimizebutton();
        nimLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();

        MainPanel.setLayout(new java.awt.CardLayout());
        MainPanel.add(landingButton1, "landing");
        MainPanel.add(menuQuest, "menuQuest");
        MainPanel.add(EntryListing, "entrylisting");
        MainPanel.add(EntryQuest, "entryquest");
        MainPanel.add(updateListing1, "updatelisting");
        updateListing1.getAccessibleContext().setAccessibleName("");

        MainPanel.add(updateQuest1, "updatequest");
        MainPanel.add(menuListing, "menuListing");

        closeminbutton1.setText("");

        minimizebutton1.setText("");

        nimLabel.setFont(new java.awt.Font("Tekton Pro", 0, 28)); // NOI18N
        nimLabel.setForeground(new java.awt.Color(48, 179, 216));
        nimLabel.setText("12.7403");

        namaLabel.setFont(new java.awt.Font("Tekton Pro", 0, 28)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(48, 179, 216));
        namaLabel.setText("12.7403");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(navbarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaLabel)
                    .addComponent(nimLabel)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(minimizebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeminbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeminbutton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizebutton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(navbarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sp.panelcomponent.DataEntryListing EntryListing;
    private sp.panelcomponent.DataEntryQuest EntryQuest;
    private javax.swing.JPanel MainPanel;
    private sp.background.Background background1;
    private sp.componentButton.Closeminbutton closeminbutton1;
    private sp.panelcomponent.LandingButton landingButton1;
    private sp.panelcomponent.Menu menuListing;
    private sp.panelcomponent.Menu menuQuest;
    private sp.componentButton.Minimizebutton minimizebutton1;
    private javax.swing.JLabel namaLabel;
    private sp.panelcomponent.NavbarButton navbarButton1;
    private javax.swing.JLabel nimLabel;
    private sp.panelcomponent.UpdateListing updateListing1;
    private sp.panelcomponent.UpdateQuest updateQuest1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the controller
     */
    public LandingMenuControllerTest getController() {
        return controller;
    }

    /**
     * @return the MainPanel
     */
    public javax.swing.JPanel getMainPanel() {
        return MainPanel;
    }

    /**
     * @return the background1
     */
    public sp.background.Background getBackground1() {
        return background1;
    }

    /**
     * @return the closeminbutton1
     */
    public sp.componentButton.Closeminbutton getCloseminbutton1() {
        return closeminbutton1;
    }

    /**
     * @return the dataEntryQuest1
     */
    public sp.panelcomponent.DataEntryQuest getDataEntryQuest1() {
        return getEntryQuest();
    }

    /**
     * @return the landingButton1
     */
    public sp.panelcomponent.LandingButton getLandingButton1() {
        return landingButton1;
    }

    /**
     * @return the menu1
     */
    public sp.panelcomponent.Menu getMenu1() {
        return getMenuListing();
    }

    /**
     * @return the minimizebutton1
     */
    public sp.componentButton.Minimizebutton getMinimizebutton1() {
        return minimizebutton1;
    }

    public JLabel getNamaLabel() {
        return namaLabel;
    }

    public void setNamaLabel(JLabel namaLabel) {
        this.namaLabel = namaLabel;
    }

    /**
     * @return the navbarButton1
     */
    public sp.panelcomponent.NavbarButton getNavbarButton1() {
        return navbarButton1;
    }

    /**
     * @return the updateQuest1
     */
    public sp.panelcomponent.UpdateQuest getUpdateQuest1() {
        return updateQuest1;
    }

    /**
     * @return the EntryListing
     */
    public sp.panelcomponent.DataEntryListing getEntryListing() {
        return EntryListing;
    }

    /**
     * @return the EntryQuest
     */
    public sp.panelcomponent.DataEntryQuest getEntryQuest() {
        return EntryQuest;
    }

    /**
     * @return the menuListing
     */
    public sp.panelcomponent.Menu getMenuListing() {
        return menuListing;
    }

    /**
     * @return the menuQuest
     */
    public sp.panelcomponent.Menu getMenuQuest() {
        return menuQuest;
    }

    /**
     * @return the updateListing1
     */
    public sp.panelcomponent.UpdateListing getUpdateListing1() {
        return updateListing1;
    }

    /**
     * @return the nimLabel
     */
    public javax.swing.JLabel getNimLabel() {
        return nimLabel;
    }
}
